### ISSUE TITLE
Fallible constructors

### ISSUE THREAD

**Issue by holykol** [gear-tech/sails#125]
### Problem to Solve

* Currently we don't support error reporting in constructors
* The only way for a program to signal that the constructor has failed is to panic and abort execution
* We don't want to leave program in corrupted state so **not** panicking is not an option
* At the same time we want some standard mechanism of reporting errors and representing possible errors in IDL.

### Possible Solution

Allow for optional Result type in program constructor that will panic for the user:
```rust
impl MyProgram {
    // Current implementation
    pub async fn new(p1: u32) -> Self {
        if p1 > 10 {
            panic!("too large")
        }
        Self { p1 }
    }

    // Proposed way
    pub async fn new_checked(p: u32) -> Result<Self, InitializeError> {
        if p > 10 {
            return Err(InitializeError::TooLarge)
            // Panic will be generated
        }
        Self { p }
        // in case of success we will send the caller `Ok(())` to signal successful initialization
    }
}
```

Using second way will allow clients to parse errors out of panic messages. It's possible, right? 

generated IDL will look like:
```
constructor {
    New : (p: u32);
    NewChecked : (param: u32) -> result (Self, InitializeError).
};
```

Maybe we should even force framework users to always use `Result` version to disincentivize panicking directly. 

### Notes

Additional inspirations: 

Error handling in Anchor:
https://docs.rs/anchor-lang/latest/anchor_lang/macro.error.html
https://docs.rs/anchor-lang/latest/anchor_lang/macro.err.html

**Comment by DennisInSky** [comment]
Having fallible ctors is considered a bad practice
