### ISSUE TITLE
Optional path in `#[groute]`

### ISSUE THREAD

**Issue by ark0f** [gear-tech/sails#178]
### Proposal

Currently empty path looks like `#[groute("")]` which can be just `#[groute]` instead

**Comment by DennisInSky** [comment]
In #187 we are going to forbid using unnamed services at all. So this issue becomes irrelevant

**Comment by DennisInSky** [comment]
Close this issue as empty routes are not allowed any longer. There might be another issue though with regards to the fact that `groute` attribute is allowed w/o any parameters at all. Atm it is just a no-op, but an error could be emitted
