### ISSUE TITLE
Use `gcore` or `gstd` simple types

### ISSUE THREAD

**Issue by ark0f** [gear-tech/sails#181]
### Proposal

`sails` define its own `ActorId`, `MessageId`, `CodeId`. Can we use `gcore` or `gstd` for convenient conversions?

**Comment by DennisInSky** [comment]
We had a conversation with @breathx and @osipov-mit and decided `gstd`'s ActorId, MessageId, CodeId will be treated as builtin types by IDL generation process.

**Comment by DennisInSky** [comment]
Waiting for https://github.com/gear-tech/gear/issues/2944
