### ISSUE TITLE
feat(gservice): consider impl `#[panicking]` macro for fns in service

### ISSUE THREAD

**Issue by breathx** [gear-tech/sails#262]
The macro will require Result in return type, but it only will be for ability to use `?`. On expand it will unwrap() the result and return only Ok(T)

**Comment by DennisInSky** [comment]
@breathx can you please elaborate on this? Any examples of usage?

**Comment by DennisInSky** [comment]
fn mint(&nut self, value: u64) -> bool {
   ler r: Result<bool, String> = some_func();
   r.unwrap(); // intentionally
}

#[panicking]
fn mint(&nut self, value: u64) -> Result<bool, String> {
   ler r: Result<bool, String> = some_func()?;
}

**Comment by vobradovich** [comment]
Wouldn't it be better to use the existing `route` attribute with the `unwrap_result` prameter?

```
#[route(unwrap_result)]
fn mint(&nut self, value: u64) -> Result<bool, String> {
    ler r: Result<bool, String> = some_func()?;
}
```

**Comment by vobradovich** [comment]
Decided to add a new `export` attribute that applies to fn implementations in services.
Only one of `export` or `route` should be used.

```rust
#[service]
impl MyService {
    #[export(route = "something", unwrap_result)]
    pub fn do_something(&mut self) -> Result<u32, String> {
        Ok(0)
    }
}
```

@DennisInSky @breathx
