### ISSUE TITLE
How to reply with value

### ISSUE THREAD

**Issue by btwiuse** [gear-tech/sails#475]
### Problem

I'd like to make a bank program with a withdraw method which returns previously deposited fund to the caller.

In gstd I was able to implement it by specifying a nonzero value in `msg::reply(payload, value)`

Sails doesn't seem to allow a custom value to be returned with the result, or am I missing something?

### Steps

-

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by DennisInSky** [comment]
At the moment there are no any special means for returning `value` with reply. What you can try to do instead is spending a regular message to the source address with some value `msg::send(payload, value)`
