### ISSUE TITLE
Unable to use macros with "renamed" sails package

### ISSUE THREAD

**Issue by breathx** [gear-tech/sails#580]
### Problem

if I put this in toml
sails = { package = "sails-rs", version = "*" }
macros will fail. need to handle it somehow (maybe analogue with codec/scaleinfo macros)

### Steps

/ .. /

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by vobradovich** [comment]
Renamed crate is supported via `crate` parameter
`#[program(crate = sails_rename)]
`
See proxy example https://github.com/gear-tech/sails/blob/master/examples/proxy/src/lib.rs
